services:
  next-app:
    container_name: next-app
    build:
      dockerfile: dev.Dockerfile

    # Set environment variables directly in the compose file
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}

    # Set environment variables based on the .env file
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - app_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  db:
    driver: local

networks:
  app_network:
    external: true