services:
  next-app-prod:
    container_name: next-app-prod
    build:
      dockerfile: prod.Dockerfile
    # Set environment variables directly in the compose file
    environment:
      NODE_ENV: 'production'
      APP_PUBLIC_URL: 'http://localhost:3000'
      GOOGLE_CLIENT_ID: ''
      GOOGLE_CLIENT_SECRET: ''
      NEXTAUTH_URL: 'http://localhost:3000'
      NEXTAUTH_SECRET: ''
      DATABASE_URL: ''

    ports:
      - 3000:3000
    networks:
      - app_network
    depends_on:
      - postgres-prod

  postgres-prod:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - app_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  db:
    driver: local

networks: 
  app_network:
    external: true